#!/bin/bash

COLOR1="#00FF90"
COLOR2="#00A45D"

used=$(echo $(df -h / | sed -n '1!p') | cut -d' ' -f3)
total=$(echo $(df -h / | sed -n '1!p') | cut -d' ' -f2)

echo "^b$COLOR1^^c$COLOR2^  ^c$COLOR1^^b$COLOR2^ $used/$total ^d^"
